### ISSUE TITLE
Incorrect endpoint in Apps API description

### ISSUE THREAD

**Issue by mmuzny** [unioslo/tsd-api-docs#3]
The endpoint incorrectly refers to Survey API at the section, where referring about deleting data using Apps API

```
DELETE /v1/p11/survey/1234/submissions?where=data=eq.1
Authorization: Bearer $token
```

**Comment by leondutoit** [comment]
Fixed in https://github.com/unioslo/tsd-api-docs/commit/b17d9bc4086be797a938b6f63813a49e2c552c53
