### ISSUE TITLE
Typo in Completing the resumable download section 

### ISSUE THREAD

**Issue by mmuzny** [unioslo/tsd-api-docs#6]
Typo in Completing the resumable download section - question mark instead of ampersand in the URL

PATCH /v1/p11/files/stream/filename?chunk=<num>?id=<UUID>&group=<group-name>

**Comment by leondutoit** [comment]
Fixed in https://github.com/unioslo/tsd-api-docs/commit/16d47cea5e8bffd108110e74a9c4877b05c8add1
